//=========================================================
// src/01_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

#define ENABLE 0
#define DISABLE 1
#define VDD 3.3
#define R_REF 10000
#define ADC_DATA_MAX 4096
#define SCALE VDD/ADC_DATA_MAX

volatile uint16_t ADC0_data;
uint16_t ADC0_data_temp = 0;
float R_measure = 0;
float Volts_temp = 0;


//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
float calculate_R(float V_out)
{
  return (V_out*R_REF)/(VDD-V_out);
}

float to_Volts(uint16_t ADC_data)
{
  return ADC_data*SCALE;
}

int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

      IE_EA = ENABLE;
      ADC0_data_temp = ADC0_data;
      IE_EA = DISABLE;

      Volts_temp = to_Volts(ADC0_data_temp);

      R_measure = calculate_R(Volts_temp);
  }                             
}
