//=========================================================
// src/01_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

#define ADC0_DATA_MAX 1024
#define MV_SCALE 1000
#define VDD 3.3

typedef unsigned short ushort;
typedef unsigned char uchar;

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}


ushort measureADC0()
{
  ADC0CN0_ADINT = 0;
  ADC0CN0_ADBUSY = 1;
  while(!ADC0CN0_ADINT);
  return ADC0;
}

float getADC0DataIn_mV(ushort ADC0Data)
{
  return (((float)ADC0Data*VDD)/ADC0_DATA_MAX)*MV_SCALE;
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  ushort ADC0Data = 0;
  float ADC0Data_mV = 0.0;

  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$
    ADC0Data = measureADC0();
    ADC0Data_mV= getADC0DataIn_mV(ADC0Data);
  }                             
}
