//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#define CLEAR 0
#define DONE 1
extern uint8_t UART_data_RX;
extern uint8_t UART_data_TX;

//-----------------------------------------------------------------------------
// UART0_ISR
//-----------------------------------------------------------------------------
//
// UART0 ISR Content goes here. Remember to clear flag bits:
// SCON0::RI (Receive Interrupt Flag)
// SCON0::TI (Transmit Interrupt Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (UART0_ISR, UART0_IRQn)
  {
    if(SCON0_RI == DONE) {
         UART_data_RX = SBUF0;
    }
    if(SCON0_TI == DONE) {
        SBUF0 = UART_data_TX;
    }
    SCON0_RI = CLEAR;
    SCON0_TI = CLEAR;
  }

